### PR TITLE
Fix Missing comments

### PR DESCRIPTION
**Pull request by gersonmontenegro**
When I'm studying from the web app, I'm struggling with missing comments.

**Steps to reproduce:**
- Open a lesson with at least 2 comments spaces, such as , such as [https://sabbath-school.adventech.io/es/2024-01/10/01](https://sabbath-school.adventech.io/es/2024-01/10/01)
- Write a comment in the first text area.
- Write a comment in the next text area and so on.
- Try to recharge the page

**Actual result**
Only the last comment modified or created is stored.

**Expected result:**
Store all the comments that I've written.

**What was modified?**
Instead to send the current comment, now all comments are stored in an Array, and send them as pack:
```
    .on("input propertychange", function() {
      commentsArray[$(this).attr("id")] = $(this).val();
      
      if (timeout !== null) {
        clearTimeout(timeout);
      }
      timeout = setTimeout(function () {
        self.saveComments(commentsArray);
      }, 2000);
    });

```
saveComments function now receive an Array, instead a unique comment, and input id:
```
    saveComments: async function (commentsArray) {
      if (!authStore().isLoggedIn) return
      try {
        const comments = Object.keys(commentsArray).map(key => ({
          comment: commentsArray[key],
          elementId: key
        }));
        await this.$apiAuth.post(`/comments`, {
          readIndex: this.readIndex,
          comments: comments
        })
      } catch (e) {}
    },
```

### CODE REVIEW

**Comment by VitalikL** [comment]
Thank you @gersonmontenegro . This indeed fixes the issue. Can you please remove `package-lock.json` from the PR.

**Review by VitalikL — CHANGES_REQUESTED** [review]
Please remove `package-lock` from the commit.

**Comment by gersontpm** [comment]
done. Thanks a lot! :-)

**Comment by VitalikL** [comment]
@gersontpm @gersonmontenegro I think you actually removed the file and committed. Can you please just remove it from the PR (i.e reset to the HEAD)

**Comment by gersonmontenegro** [comment]
sorry about that. Done.

**Review by VitalikL — APPROVED** [review]

**Pull request merged**
